### ISSUE TITLE
Adyen::API::SimpleSOAPClient::ClientError

### ISSUE THREAD

**Issue by heldopslippers** [wvanbergen/adyen#122]
Hi Guys, 

For me the Adyen::API.authorise_recurring_payment doesn't seems to work. 
Does anybody have the same problems? 

```Ruby
response = Adyen::API.authorise_recurring_payment invoice.id.to_s,
      { :currency => 'EUR', :value => 3000 },
      { :reference => invoice.user.id.to_s, :email => invoice.user.email, :statement => "invoice number #{invoice.invoice_number} "}
response.authorised?

```

This is the code I use. And ofcource have set my merchant account:
```Ruby
Adyen.configuration.default_api_params[:merchant_account] = 'merchantaccount'
```

The error is not very descriptive:
```Ruby
Adyen::API::SimpleSOAPClient::ClientError: Adyen::API::SimpleSOAPClient::ClientError
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/adyen-1.6.0/lib/adyen/api/simple_soap_client.rb:126:in `block in call_webservice_action'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/adyen-1.6.0/lib/adyen/api/simple_soap_client.rb:123:in `call_webservice_action'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/adyen-1.6.0/lib/adyen/api/payment_service.rb:86:in `make_payment_request'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/adyen-1.6.0/lib/adyen/api/payment_service.rb:55:in `authorise_recurring_payment'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/adyen-1.6.0/lib/adyen/api.rb:211:in `authorise_recurring_payment'
	from /Users/heldopslippers1/Sites/oppasapp/app/workers/create_recurring_adyen_payment_worker.rb:6:in `perform'
	from (irb):1
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:90:in `start'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/console.rb:9:in `start'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/heldopslippers1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

```

**Comment by wvanbergen** [comment]
Closing this; The SOAP client (`Adyen::API`) is deprecated. Please move to `Adyen::REST` which is better tested. If you still have issues with that API, please open a new ticket.
