### ISSUE TITLE
Problem with Android SDK integration

### ISSUE THREAD

**Issue by m-glebova** [wvanbergen/adyen#178]
Hi guys, I have a problem running your example on Android (checkoutdemo), I cloned the latest version. The log is attached below. My API configuration looks like this:
SERVER_URL: https://checkout-test.adyen.com/services/PaymentSetupAndVerification/v31/
API_HEADER_KEY: X-API-Key
API_KEY: Checkout API Key from the Web Service User (for some strange reason Checkout Demo Server API Key does not work for me)
<pre>com.adyen.checkoutdemo E/PaymentBroadcastReceivers: Provided payment data response is invalid
                                                                                 org.json.JSONException: No value for publicKeyToken
                                                                                     at org.json.JSONObject.get(JSONObject.java:392)
                                                                                     at org.json.JSONObject.getString(JSONObject.java:553)
                                                                                     at com.adyen.core.models.PaymentResponse.<init>(PaymentResponse.java:54)
                                                                                     at com.adyen.core.PaymentBroadcastReceivers$2.completionWithPaymentData(PaymentBroadcastReceivers.java:57)
                                                                                     at com.adyen.checkoutdemo.MainActivity$1$1.onSuccess(MainActivity.java:65)
                                                                                     at com.adyen.core.utils.AsyncHttpClient$1.onNext(AsyncHttpClient.java:74)
                                                                                     at com.adyen.core.utils.AsyncHttpClient$1.onNext(AsyncHttpClient.java:55)
                                                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                                     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                     at android.os.Handler.handleCallback(Handler.java:789)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767
</pre>  After setting publicKeyToken like this:
<pre>
JSONObject jsonObject = null;
try {
jsonObject = new JSONObject(new String(response, Charset.forName("UTF-8")));
jsonObject.put("publicKeyToken", token);
} catch (JSONException e) {
 e.printStackTrace();
}
paymentDataCallback.completionWithPaymentData(jsonObject.toString().getBytes());
</pre> this problem seems to be fixed, but the payment is still unsuccessful with another error in logs:
"E/CreditCardFragment: Public key is not available; credit card payment cannot be handled",
which I can't fix, because I don't have access to the CreditCardFragment initialization.
Please help me, because it's stopper for the SDK integration

**Comment by wvanbergen** [comment]
This is a community-developed client for the Ruby language only, so we cannot really help you with this. Sorry!
